-- No database seed is required for Works.
-- Add and maintain homepage projects in src/data/projects.ts instead.
-- Private Photo/Food records are intentionally not seeded because their
-- matching local or legacy Storage objects must exist before rows are useful.
