"use client";
/* eslint-disable @next/next/no-img-element -- authenticated same-origin media must remain canvas-readable */

import { useEffect, useMemo, useRef, useState } from "react";
import type { CalendarDayPayload, CalendarEntryView, CalendarMonthDay } from "@/lib/calendar/contracts";
import styles from "./CalendarPage.module.css";

const WEEKDAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
type PointLayer = { type: "text" } | { type: "sticker"; index: number };
async function jsonRequest<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, init); const body = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) throw new Error(body.error || "请求失败。"); return body as T; }
function preview(entry: CalendarEntryView | null) { return entry?.assets.find((asset) => asset.role === "preview")?.url; }

export default function CalendarExperience({ year, month, today, initialDays }: { year: number; month: number; today: { year: number; month: number; day: number }; initialDays: CalendarMonthDay[] }) {
  const [days, setDays] = useState(initialDays), [openDate, setOpenDate] = useState<string | null>(null), [day, setDay] = useState<CalendarDayPayload | null>(null), [loading, setLoading] = useState(false), [error, setError] = useState("");
  const first = (new Date(Date.UTC(year, month - 1, 1)).getUTCDay() + 6) % 7, count = new Date(Date.UTC(year, month, 0)).getUTCDate(), cells = Math.ceil((first + count) / 7) * 7;
  const dayMap = useMemo(() => new Map(days.map((item) => [item.date, item])), [days]); const grid = Array.from({ length: cells }, (_, index) => { const value = index - first + 1; return value >= 1 && value <= count ? value : null; });
  async function open(value: string) { setOpenDate(value); setLoading(true); setError(""); setDay(null); try { setDay(await jsonRequest(`/api/private/calendar/days/${value}`)); } catch (reason) { setError(reason instanceof Error ? reason.message : "无法读取当天内容。"); } finally { setLoading(false); } }
  function entryChanged(entry: CalendarEntryView) { setDay((current) => current ? { ...current, entry } : current); setDays((current) => { const found = current.some((item) => item.date === entry.date); return found ? current.map((item) => item.date === entry.date ? { ...item, entry } : item) : [...current, { date: entry.date, photoCount: 0, foodCount: 0, entry }]; }); }
  return <><div className={styles.calendarScroll}><div className={styles.calendar} role="grid" aria-label={`${year} 年 ${month} 月月历`}><div className={styles.weekHeader} role="row">{WEEKDAYS.map((value) => <div role="columnheader" key={value}>{value}</div>)}</div><div className={styles.dayGrid}>{grid.map((value, index) => {
    if (!value) return <div className={styles.emptyDay} aria-hidden="true" key={`empty-${index}`} />;
    const date = `${year}-${String(month).padStart(2, "0")}-${String(value).padStart(2, "0")}`, info = dayMap.get(date), image = preview(info?.entry ?? null), active = Boolean(info && (info.photoCount || info.foodCount || info.entry)), isToday = year === today.year && month === today.month && value === today.day;
    return <button key={date} type="button" className={`${styles.dayCell} ${active ? styles.hasContent : ""} ${isToday ? styles.today : ""}`} onClick={() => active && open(date)} disabled={!active} aria-label={`${date}${active ? `，${info?.photoCount ?? 0} 张照片，${info?.foodCount ?? 0} 条美食记录` : "，暂无内容"}`}>{image ? <img src={image} alt="" className={styles.cellPreview} /> : null}<time dateTime={date} className={styles.dayNumber}>{value}</time>{info?.entry && !image ? <span className={styles.entryState}>{info.entry.status === "ready" ? "已保存" : info.entry.status === "failed" ? "生成失败" : "草稿"}</span> : null}{active && !image ? <span className={styles.sourceDots} aria-hidden="true">{info?.photoCount ? "PHOTO" : ""}{info?.foodCount ? " FOOD" : ""}</span> : null}</button>;
  })}</div></div></div>{openDate ? <DayDialog key={`${openDate}-${loading}`} date={openDate} day={day} loading={loading} error={error} onClose={() => setOpenDate(null)} onEntryChange={entryChanged} /> : null}</>;
}

function DayDialog({ date, day, loading, error, onClose, onEntryChange }: { date: string; day: CalendarDayPayload | null; loading: boolean; error: string; onClose: () => void; onEntryChange: (entry: CalendarEntryView) => void }) {
  const [selected, setSelected] = useState<string[]>(() => day?.sources.map((source) => `${source.type}:${source.id}`) ?? []), [note, setNote] = useState(() => day?.entry?.userNote ?? ""), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [onClose]);
  async function generate() { if (!selected.length) return setMessage("请至少选择一条素材。"); setBusy(true); setMessage(""); try { const result = await jsonRequest<{ entry: CalendarEntryView }>(`/api/private/calendar/days/${date}/generate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sourceIds: selected, userNote: note }) }); onEntryChange(result.entry); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "生成失败。"); } finally { setBusy(false); } }
  return <div className={styles.backdrop} onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section role="dialog" aria-modal="true" aria-labelledby="day-dialog-title" className={styles.dialog}><header className={styles.dialogHeader}><div><p>Daily archive</p><h2 id="day-dialog-title">{date}</h2></div><button type="button" onClick={onClose} aria-label="关闭">×</button></header>{loading ? <p className={styles.dialogStatus}>正在翻找这一天…</p> : error ? <p className={styles.dialogStatus}>{error}</p> : day ? <div className={styles.dialogBody}>
    <div className={styles.sourceColumn}><p className={styles.sectionLabel}>当天素材 · 可取消不想发送给 AI 的内容</p>{day.sources.map((source) => { const key = `${source.type}:${source.id}`; return <article className={styles.sourceCard} key={key}><label><input type="checkbox" checked={selected.includes(key)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, key] : current.filter((item) => item !== key))} /><span>{source.type === "photo" ? "Photo" : "Food"}</span></label><div className={styles.sourceImages}>{source.imageUrls.map((url) => <img src={url} alt="" key={url} />)}</div><h3>{source.title}</h3>{source.description ? <p>{source.description}</p> : null}{source.comments.map((comment) => <blockquote key={comment.id}><b>{comment.author}</b>：{comment.content}</blockquote>)}</article>; })}{day.sources.length === 0 ? <p className={styles.dialogStatus}>这一天还没有可用素材。</p> : null}</div>
    <div className={styles.creationColumn}>{day.entry?.layout ? <JournalEditor key={day.entry.updatedAt} entry={day.entry} onSaved={onEntryChange} /> : <div className={styles.blankCanvas}><span>{date.slice(8)}</span><p>选择素材后生成<br />这一日的手账</p></div>}<label className={styles.noteField}><span>写给 AI 的补充</span><textarea value={note} maxLength={2000} onChange={(event) => setNote(event.target.value)} placeholder="心情、想强调的片段，或不希望出现的内容…" /></label><button className={styles.primaryButton} type="button" disabled={busy || !day.aiAvailable || day.sources.length === 0} onClick={generate}>{busy ? "生成中，请稍候…" : day.entry ? "重新生成" : "生成 Cover、文字与贴纸"}</button>{!day.aiAvailable ? <p className={styles.helper}>服务端尚未配置 CALENDAR_AI_API_KEY。</p> : null}{message ? <p className={styles.helper}>{message}</p> : null}</div>
  </div> : null}</section></div>;
}

function JournalEditor({ entry, onSaved }: { entry: CalendarEntryView; onSaved: (entry: CalendarEntryView) => void }) {
  const [layout, setLayout] = useState(entry.layout!), [text, setText] = useState(entry.finalText), [selected, setSelected] = useState<PointLayer>({ type: "text" }), [busy, setBusy] = useState(false), [message, setMessage] = useState(""); const canvasRef = useRef<HTMLDivElement>(null);
  const cover = entry.assets.find((asset) => asset.id === layout.cover.assetId); const stickers = layout.stickers.map((item) => ({ ...item, asset: entry.assets.find((asset) => asset.id === item.assetId) })).filter((item) => item.asset);
  function changePoint(layer: PointLayer, x: number, y: number) { setLayout((current) => layer.type === "text" ? { ...current, text: { ...current.text, x, y } } : { ...current, stickers: current.stickers.map((item, index) => index === layer.index ? { ...item, x, y } : item) }); }
  function pointerDown(event: React.PointerEvent, layer: PointLayer) { event.preventDefault(); setSelected(layer); const target = event.currentTarget as HTMLElement; target.setPointerCapture(event.pointerId); const rect = canvasRef.current!.getBoundingClientRect(); const move = (next: PointerEvent) => changePoint(layer, Math.max(0, Math.min(1, (next.clientX - rect.left) / rect.width)), Math.max(0, Math.min(1, (next.clientY - rect.top) / rect.height))); const end = () => { target.removeEventListener("pointermove", move); target.removeEventListener("pointerup", end); }; target.addEventListener("pointermove", move); target.addEventListener("pointerup", end); }
  function keyMove(event: React.KeyboardEvent, layer: PointLayer) { const current = layer.type === "text" ? layout.text : layout.stickers[layer.index], step = event.shiftKey ? .04 : .01; const delta = ({ ArrowLeft: [-step, 0], ArrowRight: [step, 0], ArrowUp: [0, -step], ArrowDown: [0, step] } as Record<string, number[]>)[event.key]; if (!delta) return; event.preventDefault(); changePoint(layer, Math.max(0, Math.min(1, current.x + delta[0])), Math.max(0, Math.min(1, current.y + delta[1]))); }
  async function loadImage(url: string) { return new Promise<HTMLImageElement>((resolve, reject) => { const value = new Image(); value.onload = () => resolve(value); value.onerror = reject; value.src = url; }); }
  async function renderPreview() { const canvas = document.createElement("canvas"); canvas.width = canvas.height = 1024; const context = canvas.getContext("2d")!; context.fillStyle = "#d8d9d5"; context.fillRect(0, 0, 1024, 1024); if (cover) { const source = await loadImage(cover.url), size = Math.min(source.width, source.height) / layout.cover.scale, sx = Math.max(0, Math.min(source.width - size, source.width * layout.cover.cropX - size / 2)), sy = Math.max(0, Math.min(source.height - size, source.height * layout.cover.cropY - size / 2)); context.drawImage(source, sx, sy, size, size, 0, 0, 1024, 1024); } for (const sticker of stickers) { const source = await loadImage(sticker.asset!.url), width = sticker.width * 1024, height = width * source.height / source.width; context.save(); context.translate(sticker.x * 1024, sticker.y * 1024); context.rotate(sticker.rotation * Math.PI / 180); context.drawImage(source, -width / 2, -height / 2, width, height); context.restore(); } context.fillStyle = layout.text.style.color; context.font = "42px Georgia"; context.textAlign = layout.text.style.align; context.shadowColor = "rgba(0,0,0,.35)"; context.shadowBlur = 8; const maxWidth = layout.text.width * 1024, words = Array.from(text), lines: string[] = []; let line = ""; for (const word of words) { const test = line + word; if (context.measureText(test).width > maxWidth && line) { lines.push(line); line = word; } else line = test; } lines.push(line); const anchor = layout.text.style.align === "left" ? 0 : layout.text.style.align === "center" ? maxWidth / 2 : maxWidth; lines.slice(0, 6).forEach((value, index) => context.fillText(value, layout.text.x * 1024 + anchor, layout.text.y * 1024 + index * 56, maxWidth)); return new Promise<Blob>((resolve, reject) => canvas.toBlob((blob) => blob ? resolve(blob) : reject(new Error("无法创建预览图。")), "image/png")); }
  async function save() { setBusy(true); setMessage(""); try { const blob = await renderPreview(), previewResponse = await fetch(`/api/private/calendar/entries/${entry.id}/preview`, { method: "PUT", headers: { "Content-Type": "image/png" }, body: blob }); if (!previewResponse.ok) throw new Error("预览图保存失败。"); const result = await jsonRequest<{ entry: CalendarEntryView }>(`/api/private/calendar/entries/${entry.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ finalText: text, layout, updatedAt: entry.updatedAt }) }); onSaved(result.entry); setMessage("已保存到月历。"); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "保存失败。"); } finally { setBusy(false); } }
  const activeIndex = selected.type === "sticker" ? selected.index : -1;
  const active = activeIndex >= 0 ? layout.stickers[activeIndex] : null;
  return <div className={styles.editor}><div className={styles.canvas} ref={canvasRef} style={{ backgroundImage: cover ? `url(${cover.url})` : undefined, backgroundPosition: `${layout.cover.cropX * 100}% ${layout.cover.cropY * 100}%`, backgroundSize: `${layout.cover.scale * 100}%` }}><button type="button" className={`${styles.textLayer} ${selected.type === "text" ? styles.selectedLayer : ""}`} style={{ left: `${layout.text.x * 100}%`, top: `${layout.text.y * 100}%`, width: `${layout.text.width * 100}%`, color: layout.text.style.color, textAlign: layout.text.style.align }} onPointerDown={(event) => pointerDown(event, { type: "text" })} onKeyDown={(event) => keyMove(event, { type: "text" })}>{text}</button>{stickers.map((sticker, index) => <button type="button" key={sticker.assetId} className={`${styles.stickerLayer} ${selected.type === "sticker" && selected.index === index ? styles.selectedLayer : ""}`} style={{ left: `${sticker.x * 100}%`, top: `${sticker.y * 100}%`, width: `${sticker.width * 100}%`, transform: `translate(-50%, -50%) rotate(${sticker.rotation}deg)` }} onPointerDown={(event) => pointerDown(event, { type: "sticker", index })} onKeyDown={(event) => keyMove(event, { type: "sticker", index })}><img src={sticker.asset!.url} alt={`贴纸 ${index + 1}`} /></button>)}</div>
    <div className={styles.editorControls}><label>手账文字<textarea value={text} maxLength={4000} onChange={(event) => setText(event.target.value)} /></label><div className={styles.controlRow}><label>Cover 缩放<input type="range" min="1" max="4" step=".05" value={layout.cover.scale} onChange={(event) => setLayout({ ...layout, cover: { ...layout.cover, scale: Number(event.target.value) } })} /></label>{active ? <><label>贴纸大小<input type="range" min=".05" max=".7" step=".01" value={active.width} onChange={(event) => setLayout({ ...layout, stickers: layout.stickers.map((item, index) => index === activeIndex ? { ...item, width: Number(event.target.value) } : item) })} /></label><label>旋转<input type="range" min="-180" max="180" value={active.rotation} onChange={(event) => setLayout({ ...layout, stickers: layout.stickers.map((item, index) => index === activeIndex ? { ...item, rotation: Number(event.target.value) } : item) })} /></label></> : null}</div><p className={styles.helper}>拖动图层；聚焦后用方向键精调，Shift + 方向键快速移动。</p><button type="button" className={styles.primaryButton} disabled={busy} onClick={save}>{busy ? "保存中…" : "保存到日历"}</button>{message ? <p className={styles.helper}>{message}</p> : null}</div>
  </div>;
}
